### ISSUE TITLE
What security concerns should I have with Docker? How should I go about locking it down?

### ISSUE THREAD

**Issue by BretFisher** [BretFisher/ama#17]
A common question I get.

**Comment by BretFisher** [comment]
### On Security recommendations for running Docker on servers, in order of priority of what I'd recommend.

1. Migrate everything you can in containers. Running an app in a default-settings Docker Linux container greatly reduces your risk profile vs. just running that app on a full Linux VM OS.
1. Watch my DockerCon session https://dockercon.docker.com/watch/WdAeLaLuSCNQwEp61YVXUt for some production concerns. This gives you a good baseline of production things before you dive into specific security concerns.
1. Read the docker security guide: https://docs.docker.com/engine/security/security/
1. Read some blog posts on security tools and topics. These skims a lot of things I list here: https://blog.sqreen.io/docker-security/ and https://sysdig.com/blog/20-docker-security-tools/ 
Run https://github.com/docker/docker-bench-security and see if you can improve things with your setup.

### Next level security:
1. Look up user namespaces and enable that on your prod servers so companies aren't running as root on the host. (so even if a hacker broke out of the container they are just limited user on host OS)
1. Later, check out AppArmor, SELinux, Seccomp, and Linux "capabilities" for locking down what a container can access/do on host. It's something you'll need to customize for each image you want to run, so I don't recommend them as a first step, but good for systems you really want to lock down.
1. Code scanning - use something like https://snyk.io/ to scan your repos for known vulnerabilities
1. Image scanning - docker hub used to do this, now you'll need Docker EE or 3rd party like https://github.com/coreos/clair or https://anchore.io/
1. Content Trust, which has to do with signing your code, then the images all the way through the CI/CD pipeline and finally making certain your servers won't deploy new containers on images you didn't cryptographically trust. Docker EE does this, maybe others.
1. Besides Docker EE, there are 3rd party platforms that cover many of these features like https://www.blackducksoftware.com ,  https://www.aquasec.com/ and https://www.twistlock.com/

**Comment by BretFisher** [comment]
Aqua Security now has a free basic image scanner https://github.com/aquasecurity/microscanner

**Comment by BretFisher** [comment]
For questions about "is docker secure" (what does that even mean, nothing is perfectly secure unless it's turned off and removed from the internet):

Realize that a default Docker install on Linux doesn't open ports to expose Docker remotely. This is a good thing. Even Swarm Mode only opens ports for cluster communications and requires mutual TLS auth in all cases. In version 18.09 we can even [remotely control Docker Engine through SSH](https://twitter.com/lucjuggery/status/1050750401681772544), preventing 90% of the reasons for exposing TCP ports for remote management in the first place, which is very exciting. 

The headlines we see about container security concerns largely revolve around two things:
1. **Point in time issues around bugs:** Linux bugs, like Dirty COW, which was a Linux Kernel bug that allowed something running in a container to break out of the container. It was a privilege escalation. This was a big deal but was not docker-specific. It was also not remotely executable.
2. **Ongoing issues around improper config:** Enabling the Docker Engine for remote TCP connectivity without authentication (the fault of a bad admin), or deploying Kubernetes and not enabling proper explicit auth and RBAC. You can google and see lots of cases where Kubernetes was improperly configured and you could control the cluster without a password.

**Comment by BretFisher** [comment]
Internet news: [Graboid: First-Ever Cryptojacking Worm Found in Images on Docker Hub](https://unit42.paloaltonetworks.com/graboid-first-ever-cryptojacking-worm-found-in-images-on-docker-hub/)

This goes back to same things I'm saying above:

1. **Don't run other people's images unless you trust the source.** Docker Hub, like most package managers and app stores, doesn't scan every upload to ensure safety.
1. **Don't enable the Docker TCP socket unless you secure it.** Docker [warns and educates you on the proper TLS auth for it](https://docs.docker.com/engine/security/https/), and disables it by default. Generally, it's not needed anyway, as we can now use SSH for Docker CLI-to-Engine connections, which is easier to setup, harder to mess up, and should work in 90% of remote management cases. Note that there are [authz plugins](https://docs.docker.com/engine/extend/plugins_authorization/) for Docker Engine like Docker Enterprise, https://portainer.io, and more that will provide remote TCP HTTPS access to the API, and protect it properly. These are fine too.

**Comment by BretFisher** [comment]
I did a whole YouTube Live Show on this!

[![Docker Security Top 10](https://img.youtube.com/vi/rqsrmeLn65w/0.jpg)](https://www.youtube.com/watch?v=rqsrmeLn65w)
https://www.youtube.com/watch?v=rqsrmeLn65w

**Comment by iinuwa** [comment]
Don't know if this is the place to leave follow-up questions, but I'm wondering about Portainer and the Docker socket. Point 5 says to avoid exposing the Docker socket, but Portainer requires access to the Docker socket.

It seems that a code execution vulnerability in Portainer could grant full control of the swarm and root on the host. If that is true, is there a way to mitigate this, or do we just have to trust Portainer?

**Comment by BretFisher** [comment]
On the details of the docker socket:
- I'm specifically talking about avoiding the opening of the TCP Socket to *remote Internet* connections. Portainer doesn't need the TCP port open to work, and places agents on each host that use a file socket.
- It's normal for tools to need to control Docker, such as Portainer, Traefik, etc. It's up to you if you trust these tools to have control of Docker, but just like Kubernetes, Swarm, and others, it's usually unavoidable, because you'll eventually want more then just the docker CLI to control containers.
