### ISSUE TITLE
Why do you contribute to Docker? 

### ISSUE THREAD

**Issue by alexandracyvoct** [BretFisher/ama#24]
Hey!
As part of my studies, I write a paper about the motivations to contribute to FOSS without monetary renumeration, with a focus on Docker. I will be VERY VERY grateful if you take 2 minutes of your time to complete the following survey: https://goo.gl/forms/4IR6IofUzM4fanaQ2  
Thanks a million!

**Comment by BretFisher** [comment]
URL is broken, so reopen with working URL if you want to.
