### ISSUE TITLE
Restricting access to exposed ports for only a specific container

### ISSUE THREAD

**Issue by NiharPattanaik** [BretFisher/ama#30]
Hi Bret,

I was great Docker tutorial and i enjoyed all your lectures. I have a problem i'm not able to solve, appreciate if you can help me.

In my product i have introduced a RabbitMQ container and we have already few more different containers are running on the same docker runtime. For RabbitMQ i have exposed few ports. Now the issue is how to restrict the access to these ports from outside as docker allows access to all exposed ports through iptables configuration.

I have thought of adding a new rule to drop all connections from any source in DOCKER or DOCKER-USER chain and then allowing only IPs which are supposed to access. However this will restrict the access to Docker which will impact all other containers also.
Need help on how to restrict ports exposed for my container only and then selectively allowing the access to known IPs.

Regards,
Nihar

**Comment by NiharPattanaik** [comment]
Hi Bret,
Thanks for your quick response. I'm using single docker engine and not in swarm mode. The ports are exposed using -p in docker startup. This is an on-prem product and not on the cloud, deployed on multiple nodes in a  enterprise DC. Once the port is exposed on docker, the port can be accessed by any system on that network which has IP access. But my requirement is this RabbitMQ container/application should only be accessed few of the nodes.

Regards,
Nihar

**Comment by BretFisher** [comment]
Yea I don't have an answer for you other than above. In datacenters I work in, they control that at the VLAN level the hosts are placed on.

**Comment by BretFisher** [comment]
I would think messing with iptables would get overwritten on next docker run. If you figure out a way to solve your issue please update us here to benefit others!

**Comment by NiharPattanaik** [comment]
Another option i have tried is updating the NAT rules added by Docker by specifying the source for the IPs allowed to connect. This works but when container restarts, the rules will be again over written by docker.
