### ISSUE TITLE
Containers vs Serverless for the future

### ISSUE THREAD

**Issue by 3plcentraldev** [BretFisher/ama#32]
Hello Bret, I have taken your course and saw you speak recently in southern utah.  As a big fan and the person that got me really introduced to using docker, I would be interested in your thoughts in regards regards to containers vs serverless.  Some individuals see them as competing fields, some as complimentary technologie, some as mutually exclusive.  Would be interested to hear your thoughts especially in regards to where you think this is heading in the future.

**Comment by fipnova51** [comment]
Hi all,

Thank you Bret for your valuable inputs

Simon
