### ISSUE TITLE
Docker Container Name Resolution Across Cluster

### ISSUE THREAD

**Issue by bgercken** [BretFisher/ama#34]
Good Morning Bret,

QUESTION

How can I get container name resolution to work across all nodes in a cluster (even those that are not running docker)? 

SCENARIO

I am a developing a multi node big data cluster that includes Docker, Hadoop and Spark technologies. 

The Spark Cluster is responsible for running workloads that will be accessed remotely through applications running in the containers (for example Jupyter notebooks) however the spark master and worker nodes will not be running docker. In this scenario, the worker nodes need to be able to map back to the container address to complete communication with the driver class running in the container. 

Example:

`
Spark Executor Command: "/usr/java/default/bin/java" "-cp" "/opt/spark2/conf/:/opt/spark2/jars/*" "-Xmx1024M" "-Dspark.driver.port=42537" "org.apache.spark.executor.CoarseGrainedExecutorBackend" "--driver-url" "spark://CoarseGrainedScheduler@`**8b1142c3f846**`:42537" "--executor-id" "16" "--hostname" "192.168.0.200" "--cores" "1" "--app-id" "app-20180731183316-0000" "--worker-url" "spark://Worker@192.168.0.200:36192"
`

I am looking into getting the container to expose the IP address in the originating call to the spark-master but have not figured that out yet. Note that the above call succeeds if I hand jam the host/ip address mapping in the host file on the spark master ```(172.17.0.3   8b1142c3f846)```.

I have tested `defreitas/dns-proxy-server` which works for a single node but have not figured out how I could use it across multiple hosts.

I am using docker enterprise edition if that has a bearing on the solution.

Thanks!

**Comment by bgercken** [comment]
So far...

If I am willing to move my spark components into containers (rather then running on bare metal) than an overlay network solves the problem. In this case (CODE1) I am using specific IPs so that my DNS entries match (in the hope that I could ping the container from the host as described in the original problem).

But I am still unable to ping the containers from the host network. I tried adding a route to the subnet (see CODE 2 below) but no joy. Any ideas? 

Cheers.
-bill

**CODE 1**

`
[bgercken@docker-manager ~]$  docker network create --driver=overlay --attachable --subnet=192.168.0.208/28 --gateway=192.168.0.209 container-net

[bgercken@docker-manager ~]$ docker container run -d --rm --name container1 -h container1 --net container-net --ip 192.168.0.210 alpine ping 8.8.8.8

[bgercken@titan ~]$ docker container run -d --rm --name container2 -h container2 --net container-net --ip 192.168.0.211 alpine ping 8.8.8.8
31853b87848f7c70e806f6f9c9d7b457fce6d64c0efa832b0e6991034132f453

[bgercken@titan ~]$ docker container exec -it container2 sh
/ # ping -c 1 container1
PING container1 (192.168.0.210): 56 data bytes
64 bytes from 192.168.0.210: seq=0 ttl=64 time=0.656 ms

[bgercken@docker-manager ~]$ docker container exec -it container1 sh
/ # ping -c 1 container2
PING container2 (192.168.0.211): 56 data bytes
64 bytes from 192.168.0.211: seq=0 ttl=64 time=0.557 ms

--- container2 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 0.557/0.557/0.557 ms

/ # ping -c 1 192.168.0.1
PING 192.168.0.1 (192.168.0.1): 56 data bytes
64 bytes from 192.168.0.1: seq=0 ttl=63 time=0.492 ms

--- 192.168.0.1 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 0.492/0.492/0.492 ms
`

**CODE2**

`
[root@docker-manager bgercken]# route add -net 192.168.0.208 netmask 255.255.255.240 gw 192.168.0.209

[root@docker-manager bgercken]# ping -c 1 container1
PING container1.ktdev.net (192.168.0.210) 56(84) bytes of data.
From docker-manager.ktdev.net (192.168.0.191) icmp_seq=1 Destination Host Unreachable

--- container1.ktdev.net ping statistics ---
1 packets transmitted, 0 received, +1 errors, 100% packet loss, time 0ms

[root@docker-manager bgercken]# netstat -nr
Kernel IP routing table
Destination     Gateway         Genmask         Flags   MSS Window  irtt Iface
0.0.0.0         192.168.0.1     0.0.0.0         UG        0 0          0 ens192
10.0.156.64     192.168.0.160   255.255.255.192 UG        0 0          0 tunl0
10.0.173.0      0.0.0.0         255.255.255.192 U         0 0          0 *
10.0.173.11     0.0.0.0         255.255.255.255 UH        0 0          0 calicc9e1866c3e
10.0.173.12     0.0.0.0         255.255.255.255 UH        0 0          0 calibb3849d04c0
10.0.198.64     192.168.0.200   255.255.255.192 UG        0 0          0 tunl0
172.17.0.0      0.0.0.0         255.255.0.0     U         0 0          0 docker0
172.18.0.0      0.0.0.0         255.255.0.0     U         0 0          0 docker_gwbridge
192.168.0.0     0.0.0.0         255.255.255.0   U         0 0          0 ens192
192.168.0.208   192.168.0.209   255.255.255.240 UG        0 0          0 ens192

`

**Comment by BretFisher** [comment]
Hi there, in general:

* Any work in a Swarm should be in containers. Putting anything on hosts is an anti-pattern.
* Overlay is the easiest way for everything to communicate inside a Swarm. Any other config should have a very specific reason for why you're *not* using overlay.
* If you need workloads that are not in containers, then those workloads should not be on the same hosts as a Swarm, as combining the two just adds significant complexity and also prevents Swarm nodes from being 1. disposable and 2. able to manage their resources via Service resource requirements. Once you add a node to a Docker EE Swarm, everything from then on should be deployed as a Service. This keeps with the "cattle not pet" design of Swarm clusters.
* Knowing how application resolve other members of their app is a very specific thing. I don't know your apps, sorry.

I hope that helps.

**Comment by bgercken** [comment]
Thanks Brett! It does help.

Your first and third bullets say it all. I was thinking about it this morning and realized that the java RMI model (or even J2EE for that matter) do not fit the services model that is used by containers. It can work on a single host but then we are not leveraging the advantages of the swarm.

Thanks again.
