### ISSUE TITLE
OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"./bin/run.sh\": stat ./bin/run.sh: no such file or directory": unknown. 

### ISSUE THREAD

**Issue by jawadmadani** [BretFisher/ama#38]
Hi, I am trying to run my Jenkins pipeline which is in a Docker container and I have given Jenkins container permission to create other containers based on pipeline and then delete them afterwards, it creates a container for maven and runs maven there on my project and then deletes it successfully but then when it try to create a container for SonarQube from sonarqube official image it fails somehow, below is the fail error, could you look into this if possible please. appreciate it!

[alfalah_master-U5DW6VPJXH2DJ3S6ZSODLDXUFMGIFS3WD4P4KHD4QKDX6L2N2T6A@2] Running shell script

docker inspect -f . sonarqube
.
[Pipeline] withDockerContainer
Jenkins seems to be running inside container 3505b9b14522d0c335843a61dbe9b1fcc5ba03861b9bdf23f70da172925361f5

`$ docker run -t -d -u 0:0 -w /var/jenkins_home/workspace/alfalah_master-U5DW6VPJXH2DJ3S6ZSODLDXUFMGIFS3WD4P4KHD4QKDX6L2N2T6A@2 --volumes-from 3505b9b14522d0c335843a61dbe9b1fcc5ba03861b9bdf23f70da172925361f5 -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** sonarqube cat`

[Pipeline] // withDockerContainer
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
[Bitbucket] Notifying commit build result
[Bitbucket] Build result notified

`java.io.IOException: Failed to run image 'sonarqube'. Error: docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"./bin/run.sh\": stat ./bin/run.sh: no such file or directory": unknown.`

**Comment by BretFisher** [comment]
Hey there,

I know it says "AMA", but this isn't really a good place to troubleshoot your jenkins. I recommend trying a Q&A site like stackoverflow.com.

That being said, the error `"exec: \"./bin/run.sh\": stat ./bin/run.sh: no such file or directory": unknown.` sums it up. It can't find or run that file in the container.
