### ISSUE TITLE
Docker Mastery Intro Music

### ISSUE THREAD

**Issue by ghost** [BretFisher/ama#44]
Hello Bret,

I really like the Intro Music of your famous Docker Mastery Course on Udemy. Does it have a name? Does it have a full/longer version? Can I listen to, purchase or download the track somehow?

Thx in advance and best regards,
David

**Comment by BretFisher** [comment]
It's "Pacific Hike" from YouTube's library of free music:

https://www.youtube.com/audiolibrary/music
