### ISSUE TITLE
The node is marked as down in UCP with error message "Calico-node pod is unhealthy: %!s(<nil>)".

### ISSUE THREAD

**Issue by dipanjanmukherjee83** [BretFisher/ama#49]
From manager if we run "docker node ls" it is showing "Ready" and "Active" for all the nodes that we have but from UCP end it is showing "Down" and "Calico-node pod is unhealthy" for one of the worker node.
So far we did rebooted the worker node, remove it from swarm and re-join it but still it is showing the same from UCP end. From docker site we got below two articles but we don't have kubectl binaries installed in our servers. Is there any other work around or we should go with the docker article.

https://success.docker.com/article/nodes-down-due-to-calico-node-unhealthy-on-swarm-only-cluster
https://success.docker.com/article/calico-node-unhealthy

**Comment by BretFisher** [comment]
Hi there, sorry this isn't a technical support repo, because there are much better places for that like https://forums.docker.com and https://stackoverflow.com. I would always refer to Docker's expertise on Docker Enterprise issues. Good luck!
