### ISSUE TITLE
Traefik for Docker Swarm? (load balance, replace Nginx)

### ISSUE THREAD

**Issue by 1c7** [BretFisher/ama#53]
Hi Bret!

### My Goal here: Run multiple website inside one swarm.
Because they can't all listen on 80/433.
So after some research, seem like I should use [Traefik](https://traefik.io/)

### Question
Have you plan to make some simple Traefik tutorial on Udemy or Youtube?
put this into Swarm Mastery course would be quite helpful.

Thanks
I hope this doesn't sound like I am demanding things from you. like giving you pressure or anything.
I am just curious if this already on your to-do list.
and what's the rough timeline. March/April maybe? or it's unclear

Thanks again

**Comment by 1c7** [comment]
![image](https://user-images.githubusercontent.com/1804755/52766870-8d2ddf00-3063-11e9-8543-19a8d823e65b.png)
https://github.com/BretFisher/dogvscat/blob/master/stack-proxy.yml
this is helpful. looking into it now

**Comment by 1c7** [comment]
I give up after a while, Traefik just too complicate for me at this point.
(what's with that TOML syntax? so difficult to read. why not yaml? json?)

I don't have enough time to learn Traefik(and I don't really care that much, I just want it up and running)
The official doc doesn't contain good example for me to just copy&paste.

Fallback to Nginx for now.

**Comment by guillaumemaka** [comment]
I always ask myself too why TOML (the unreadable format) ??? I read the documentation (if you call "snippets" documentation). I won't give up yet. I'll give it another try (need some red bull first)
