### ISSUE TITLE
Rolling updates with update_config:order: start-first | stop-first

### ISSUE THREAD

**Issue by dipanjanmukherjee83** [BretFisher/ama#55]
From docker compose file version 3.4 and above we can change the default behaviour of container spin-up during service update by using "order: start-first | stop-first" in “update_config” section. 
By default the Update order is "stop-first". And as per the docker docs with "start-first", the new task is started first, and the running tasks briefly overlap.  Now my question is,
we have a service in global mode with service constraints for particular node and set healthcheck instruction (curl --fail -s http://127.0.0.1:8000/ || exit 1) in stack file. Now if we set the order to start-first then after the service update new container will spin-up and will try to access open port 8000 to become healthy. So is there any port conflict happened between new and old containers because until the new container successfully pass the healthcheck it would not become ready and retries.
Is it possible at the same time both the container can access the same port on same host. We are trying to achieve zero downtime during service update. Please give some advice on this.

**Comment by 1c7** [comment]
you need format your text instead of writing it as a huge chunk.
difficult to read really

**Comment by dipanjanmukherjee83** [comment]
sorry for that. In short,  what would be the sequences for "order: start-first" option in Global mode service.
Hope it make sense.

**Comment by dipanjanmukherjee83** [comment]
Hi Bret, 
I am closing the issue #55 as because theoretically it is not possible. We are using global mode with host networking and we have tested the "start-first" order option is not working. 
During service update it stuck and showing "host-mode port already in use on 1 node". 
Because in host mode, the port is only bound on nodes where the service is running, and a given port on a node can only be bound once.
But thanks anyway.
