### ISSUE TITLE
I'm a developer, how do I become better at Sysadmin or DevOps roles?

### ISSUE THREAD

**Issue by BretFisher** [BretFisher/ama#7]
A common question from developers:

> I've been a full-stack dev for about 4 years, and ... I'm trying to figure out how to actually become a DevOps / SysAdmin guy. Any suggestions on maybe a learning path and/or which courses to take? I feel like the path is more clear for web dev, but it's been hard to find something more clear cut in the DevOps world.

Also a similar question from those just starting out:

> I am beginner and just learning the basics. just want to know what is devops? I am a system administrator but dont know about devops. how can I become a devops and what are the requirements what skill do i need?

**Comment by itprohelper** [comment]
Great explanation!

**Comment by BretFisher** [comment]
Here's a good beginner course on DevOps topics that I watched some of: https://www.linkedin.com/learning/devops-foundations

**Comment by kharels** [comment]
Thanks Bret! This definitely helps.

**Comment by Aracki** [comment]
This is a great text. You should make a blog post out of it. 👍

**Comment by BretFisher** [comment]
Good idea!

**Comment by BretFisher** [comment]
Here's an interesting learning path. 

https://github.com/kamranahmedse/developer-roadmap/#devops-roadmap

I would change it so that step one is NOT to learn a programming language unless you're a dev (in which you already know one). There are plenty of sysadmins and ops that barely know any scripting languages, much less full-featured programming languages that can do a lot in the DevOps space with CLI commands, YAML, and some JSON. I'd say yes to be a well-rounded DevOps person you'd want to know a little about multiple languages, but I find it's more helpful to know the packaging tools, the dependency and build file languages, and how apps are typically laid out on a file system. When you know that about a language you can usually take an app from the dev, properly package it up, deploy it, monitor it, and understand what it does without ever being able to write a hello world in that language.

**Comment by iamfredrickokereke** [comment]
I love this and already on this path, but this makes it clearer and relatable. Thank you so much for sharing @BretFisher.
