### ISSUE TITLE
Enable RDP in Windows containers

### ISSUE THREAD

**Issue by masoudr** [BretFisher/ama#72]
Hi,
I've followed your Docker Mastery course and I need to say thanks for that.
I have two questions:
1. Is there any way to get into a Windows container desktop. I mean in some situations I might have to install some GUI apps into my container that can't be done in the CLI. So I was wondering is there any way to that on Windows containers.

2. To follow up on my first question it seems that the only way is to use RDP. I tried some versions of Windows containers like `mcr.microsoft.com/windows/servercore`,  `mcr.microsoft.com/windows`, etc. But I couldn't enable RDP in those. Although I've followed this [tutorial](https://withinrafael.com/2018/03/09/using-remote-desktop-services-in-containers/) and the remote desktop app responds to connecting to the container but after connecting nothing happens and it seems that there is no Desktop in there.

Thanks.

**Comment by BretFisher** [comment]
Sorry no. Microsoft specifically isn't supporting RDP or GUI's in containers, as far as I know.

**Comment by masoudr** [comment]
Thanks. It seems that if there is no GUI on Windows containers, it may not be good for use in the development environment. I mean as you might know Windows developers usually rely on GUI on Windows. So it might be frustrating for them to do all the stuff using Powershell of CMD. On the other hand, some apps need GUI for installation or configuration. So how can we handle them on Windows containers, is there any other alternative?

**Comment by BretFisher** [comment]
Containers are currently ideal for non-GUI programs like server processes, CLI tools, etc. I work with Windows development teams and they are doing everything from Python/.NET/PHP server apps to .exe CLI tools inside containers, but if you're trying to develop a desktop app, then containers aren't ideal.
