### ISSUE TITLE
Windows 10 Pro install issues with 2.1

### ISSUE THREAD

**Issue by spyd3rw3b** [BretFisher/ama#76]
With Windows 10 Pro upgrades are failing due to specific settings (IOW, I got them working based on the GIT issues, which usually mean re-install), This usually drops all the local containers and volumens and I have to restore from dockerfile or reimport. what is the best practice for backing up images? Is there an easier way to say local containers when upgrading. Lastly, I'm running wsl2, and running an ubuntu 18 subsystem...is there a benefit from running docker from a wsl host?

**Comment by BretFisher** [comment]
Oops somehow I missed this issue from years ago. Hope you found your answer ;)
