### ISSUE TITLE
Hi Bret,  Can you please create a video explaining Jenkins X, I have gone through those already on the internet, not easy to grasp.  Hence this request.

### ISSUE THREAD

**Issue by parimalaprahlada** [BretFisher/ama#87]

**Comment by BretFisher** [comment]
How about https://youtu.be/SrzGzlWg7MA

**Comment by parimalaprahlada** [comment]
Wow, such quick response, I did not expect it.
Thanks a lot

**Comment by parimalaprahlada** [comment]
I have already watched this video, and only through this video, I came to know about you, your courses.
I could not resist, I have purchased your courses on Udemy, but yet to start.
Thanks for responding to my request.
