### ISSUE TITLE
Trying to run jekyll in windows 10 docker - getting error 

### ISSUE THREAD

**Issue by ntdconsulting** [BretFisher/ama#93]
![image](https://user-images.githubusercontent.com/61295273/77465881-5f26dc80-6dd7-11ea-8231-69bde6b830a5.png)
Working through udemy course and having some issues using docker on  Windows 10  in some of the lectures.   

Windows docker does not like $(pwd) for i'm using %cd%  -  assuming that is ok.  My issue is more when this container loads it is not able  to install  rubygems and abandons.  

Any ideas ?

**Comment by BretFisher** [comment]
Hey there. Course questions go in Udemy Q&A, thanks. Also check The Big FAQ in Section 1 for answers to common questions like this.
